apiVersion: v1
kind: Pod
metadata:
  name: debug-pod

spec:
  containers:
    - name: mysql-container
      image: busybox:1.35
      command: ["sleep", "3600"]
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 0
