apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
  labels:
    app: phpmyadmin
spec:
  containers:
    - name: phpmyadmin-container
      imagePullPolicy: "IfNotPresent"
      image: phpmyadmin:latest
      ports:
        - name: "phpmyadmin"
          containerPort: 80
      env:
        - name: PMA_HOST
          value: mysql-pod.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-pod

spec:
  selector:
    app: phpmyadmin
  ports:
  - targetPort: 80
    port: 10001
  type: LoadBalancer

