/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

plugins {
    id("samplepluginproject.greeting")
}

MyExtension {
    value = "GREAT NOW EXTENSION WORKS"
}